import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          '50': '#eff6ff',
          '100': '#dbeafe',
          '200': '#bfdbfe',
          '300': '#93c5fd',
          '400': '#60a5fa',
          '500': '#3b82f6',
          '600': '#2563eb',
          '700': '#1d4ed8',
          '800': '#1e40af',
          '900': '#1e3a8a',
          '950': '#172554',
        },
        palette: {
          matte: '#121212',
          black: '#0b0708',
          gray: '#2f2a24',
          red: {
            '50': '#ffcbd1',
            '100': '#f69697',
            '200': '#ee6b6e',
            '300': '#f94449',
            '400': '#ff2c2c',
            '500': '#f01e2c',
            '600': '#de0a26',
            '700': '#d1001f',
            '800': '#c30010',
            '900': '#880808',
            DEFAULT: '#99011e',
          },
          brown: '#8e5c57',
          white: '#f9f3e6',
        },
      },
    },
    fontFamily: {
      body: [
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
        'Inter',
      ],
      sans: [
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
        'Inter',
      ],
    },
  },
  plugins: [],
};
export default config;
