import ThemeProvider from '@/app/components/ui/theme-provider';
import ClientSessionProvider from '@app/components/client-session-provider';

import '@/app/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-palette-white dark:bg-palette-gray">
        <ClientSessionProvider>
          <ThemeProvider>
            <div className="w-full h-screen items-center justify-center">
              {children}
            </div>
          </ThemeProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
